import csv
from PyQt6.QtWidgets import *
from PyQt6.QtCore import Qt
from gui import *
from accounts import Account, SavingAccount


# AI assisted with PyQt6 window structure
class Logic(QMainWindow, Ui_MainWindow):
    """
    Main application window for the Bank Account Manager.
    Inherits from QMainWindow and Ui_MainWindow (generated by QT Designer).
    """

    def __init__(self) -> None:
        """Initialize the window, set up UI, and connect buttons."""
        super().__init__()
        self.setupUi(self)
        self.__current_account = None
        self.__transactions: list = []
        self.history_table.setHorizontalHeaderLabels(
            ["Account", "Transaction", "Balance After"]
        )
        self.history_table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeMode.Stretch
        )
        self.status_label.setText("")
        self.create_button.clicked.connect(self.__handle_create)
        self.deposit_button.clicked.connect(self.__handle_deposit)
        self.withdraw_button.clicked.connect(self.__handle_withdraw)
        self.save_button.clicked.connect(self.__handle_save)

    def __handle_create(self) -> None:
        """Validate input and create a new Account or SavingAccount."""
        name = self.name_input.text().strip()
        account_type = self.account_type.currentText()

        if not name:
            QMessageBox.critical(self, "Error", "Account name cannot be empty.")
            return

        if account_type == "Savings Account":
            self.__current_account = SavingAccount(name)
        else:
            self.__current_account = Account(name)

        self.__transactions = []
        balance = self.__current_account.get_balance()
        self.balance_label.setText(f"Balance: ${balance:.2f}")
        self.__add_table_row(name, "Account Created", balance)
        self.__transactions.append([name, "Account Created", f"${balance:.2f}"])
        self.status_label.setText(f"{account_type} created for {name}!")
        self.status_label.setStyleSheet("color: green;")

    def __handle_deposit(self) -> None:
        """Validate input and deposit amount into the current account."""
        if not self.__check_account_exists():
            return

        amount_text = self.amount_input.text().strip()

        try:
            amount = float(amount_text)
        except ValueError:
            QMessageBox.critical(self, "Error", "Amount must be a number.")
            return

        if amount <= 0:
            QMessageBox.critical(self, "Error",
                                 "Deposit amount must be greater than 0.")
            return

        success = self.__current_account.deposit(amount)
        if success:
            balance = self.__current_account.get_balance()
            self.balance_label.setText(f"Balance: ${balance:.2f}")
            self.__add_table_row(
                self.__current_account.get_name(),
                f"Deposit: +${amount:.2f}",
                balance
            )
            self.__transactions.append([
                self.__current_account.get_name(),
                f"Deposit: +${amount:.2f}",
                f"${balance:.2f}"
            ])
            self.status_label.setText(f"Deposited ${amount:.2f} successfully.")
            self.status_label.setStyleSheet("color: green;")
        else:
            QMessageBox.critical(self, "Error", "Deposit failed.")

        self.amount_input.clear()

    def __handle_withdraw(self) -> None:
        """Validate input and withdraw amount from the current account."""
        if not self.__check_account_exists():
            return

        amount_text = self.amount_input.text().strip()

        try:
            amount = float(amount_text)
        except ValueError:
            QMessageBox.critical(self, "Error", "Amount must be a number.")
            return

        if amount <= 0:
            QMessageBox.critical(self, "Error",
                                 "Withdrawal amount must be greater than 0.")
            return

        success = self.__current_account.withdraw(amount)
        if success:
            balance = self.__current_account.get_balance()
            self.balance_label.setText(f"Balance: ${balance:.2f}")
            self.__add_table_row(
                self.__current_account.get_name(),
                f"Withdrawal: -${amount:.2f}",
                balance
            )
            self.__transactions.append([
                self.__current_account.get_name(),
                f"Withdrawal: -${amount:.2f}",
                f"${balance:.2f}"
            ])
            self.status_label.setText(f"Withdrew ${amount:.2f} successfully.")
            self.status_label.setStyleSheet("color: green;")
        else:
            QMessageBox.critical(self, "Error",
                                 "Withdrawal failed. Check amount or minimum balance.")

        self.amount_input.clear()

    def __handle_save(self) -> None:
        """Open a file dialog and save transaction history to CSV."""
        if not self.__transactions:
            QMessageBox.critical(self, "Error", "No transactions to save.")
            return

        file_path, _ = QFileDialog.getSaveFileName(
            self, "Save Transactions", "", "CSV Files (*.csv)"
        )
        if not file_path:
            return

        try:
            with open(file_path, "w", newline="") as csv_file:
                writer = csv.writer(csv_file)
                writer.writerow(["Account", "Transaction", "Balance After"])
                for row in self.__transactions:
                    writer.writerow(row)
            QMessageBox.information(self, "Saved",
                                    f"Transactions saved to:\n{file_path}")
        except IOError as e:
            QMessageBox.critical(self, "Error", f"Could not save file: {e}")

    def __add_table_row(self, account: str, transaction: str,
                        balance: float) -> None:
        """
        Add a row to the transaction history table.

        Args:
            account (str): Account name.
            transaction (str): Transaction description.
            balance (float): Balance after transaction.
        """
        row = self.history_table.rowCount()
        self.history_table.insertRow(row)
        self.history_table.setItem(row, 0, QTableWidgetItem(account))
        self.history_table.setItem(row, 1, QTableWidgetItem(transaction))
        self.history_table.setItem(row, 2, QTableWidgetItem(f"${balance:.2f}"))

    def __check_account_exists(self) -> bool:
        """
        Check if an account has been created.

        Returns:
            bool: True if account exists, False otherwise.
        """
        if self.__current_account is None:
            QMessageBox.critical(self, "Error",
                                 "Please create an account first.")
            return False
        return True